name: Build Meffite Image

on:
  workflow_dispatch:

jobs:
  container-build:
    runs-on: ubuntu-latest
    name: Universal Blue Container Build
    container:
      image: ghcr.io/ublue-os/image-builder:main
      options: --privileged
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build image
        run: |
          podman build -t meffite .

      - name: Export image
        run: |
          container_id=$(podman create meffite)
          podman export "$container_id" > meffite.tar
          mkdir -p out
          mv meffite.tar out/

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: meffite
          path: out/
