name: Build Meffite Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Build the image
        run: |
          podman build -t meffite .

      - name: Export image
        run: |
          container_id=$(podman create meffite)
          podman export "$container_id" > meffite.tar
          mkdir -p out
          mv meffite.tar out/

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: meffite
          path: out/
