name: Build SteamOS Custom Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Podman
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Build the image
        run: |
          podman build -t meffite .

      - name: Export image as tar
        run: |
          container_id=$(podman create meffite)
          podman export $container_id > meffite.tar
          mkdir out
          mv meffite.tar out/

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: meffite
          path: out/
